import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import api from "../services/api";

const empty = { title: "", company: "", description: "", location: "", jobType: "Full-time", experienceLevel: "Entry Level", salaryMin: "", salaryMax: "", skills: "", category: "", applicationDeadline: "" };
const toForm = (job) => ({ ...empty, ...job, skills: (job.skills || []).join(", "), applicationDeadline: job.applicationDeadline ? job.applicationDeadline.slice(0, 10) : "" });

export default function Dashboard() {
  const [jobs, setJobs] = useState([]); const [applications, setApplications] = useState([]); const [form, setForm] = useState(empty); const [editingId, setEditingId] = useState(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const user = JSON.parse(localStorage.getItem("user") || "null"); const role = user?.role;
  const load = async () => { try { const [jobsRes, appRes] = await Promise.all([api.get("/jobs/recruiter/mine"), api.get("/applications/recruiter")]); setJobs(jobsRes.data.jobs); setApplications(appRes.data.applications); } catch (err) { setError(err.response?.data?.message || "Could not load dashboard data"); } };
  // Dashboard data is initialized from asynchronous API calls.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (role === "recruiter") void load(); }, [role]);
  if (role !== "recruiter") return <Navigate to="/jobs" replace />;
  const submit = async (e) => { e.preventDefault(); setError(""); const payload = { ...form, skills: form.skills.split(",").map((item) => item.trim()).filter(Boolean) }; try { if (editingId) { await api.patch(`/jobs/${editingId}`, payload); setNotice("Job updated successfully."); } else { await api.post("/jobs", payload); setNotice("Your job is now live."); } setEditingId(null); setForm(empty); await load(); } catch (err) { setError(err.response?.data?.message || "Could not save this role"); } };
  const edit = (job) => { setEditingId(job._id); setForm(toForm(job)); setNotice(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id) => { if (!window.confirm("Delete this job permanently? Existing applications will remain in your records.")) return; try { await api.delete(`/jobs/${id}`); setNotice("Job deleted."); await load(); } catch (err) { setError(err.response?.data?.message || "Could not delete this role"); } };
  const status = async (id, next) => { try { await api.patch(`/applications/${id}/status`, { status: next }); await load(); } catch (err) { setError(err.response?.data?.message || "Could not update application"); } };
  const activeJobs = jobs.filter((job) => job.status === "active").length; const shortlisted = applications.filter((app) => app.status === "shortlisted").length;
  return <section className="recruiter-page"><div className="dash-banner"><div><p className="eyebrow">Recruiter studio</p><h1>Hello, {user.name?.split(" ")[0]}.</h1><p>Make your next brilliant hire from one thoughtful workspace.</p></div><div className="dash-orb" /></div><div className="stat-grid"><div><strong>{activeJobs}</strong><span>Active roles</span></div><div><strong>{applications.length}</strong><span>Total candidates</span></div><div><strong>{shortlisted}</strong><span>Shortlisted</span></div></div>{error && <p className="alert error">{error}</p>}{notice && <p className="alert success">{notice}</p>}
    <div className="recruiter-grid"><form className="editor-card" onSubmit={submit}><div className="editor-heading"><div><p className="eyebrow">{editingId ? "Refine role" : "New opportunity"}</p><h2>{editingId ? "Edit job listing" : "Publish a role"}</h2></div>{editingId && <button type="button" className="text-button" onClick={() => { setEditingId(null); setForm(empty); }}>Cancel editing</button>}</div><div className="form-grid dark-form"><label>Job title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Company<input required value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></label><label>Location<input required value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Category<input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Engineering" /></label><label>Job type<select value={form.jobType} onChange={(e) => setForm({ ...form, jobType: e.target.value })}>{["Full-time", "Part-time", "Internship", "Contract", "Freelance"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Experience<select value={form.experienceLevel} onChange={(e) => setForm({ ...form, experienceLevel: e.target.value })}>{["Fresher", "Entry Level", "Mid Level", "Senior Level"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Minimum salary<input type="number" min="0" value={form.salaryMin} onChange={(e) => setForm({ ...form, salaryMin: e.target.value })} /></label><label>Maximum salary<input type="number" min="0" value={form.salaryMax} onChange={(e) => setForm({ ...form, salaryMax: e.target.value })} /></label><label>Deadline<input required type="date" value={form.applicationDeadline} onChange={(e) => setForm({ ...form, applicationDeadline: e.target.value })} /></label><label>Skills <small>Comma separated</small><input value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} placeholder="React, Figma, SQL" /></label><label className="full">Role description<textarea required rows="5" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div><button className="coral-button">{editingId ? "Save changes" : "Publish opportunity"}</button></form>
      <aside className="roles-panel"><div className="panel-heading"><div><p className="eyebrow">Your roles</p><h2>Hiring board</h2></div><span>{jobs.length} total</span></div>{jobs.length ? jobs.map((job) => <article className="role-row" key={job._id}><div><span className={`status-pill ${job.status}`}>{job.status}</span><h3>{job.title}</h3><p>{job.location} · {job.jobType}</p></div><div className="role-actions"><button onClick={() => edit(job)}>Edit</button><button onClick={() => remove(job._id)}>Delete</button></div></article>) : <p className="muted">Your published opportunities will live here.</p>}</aside></div>
    <section className="candidate-section"><div className="section-title"><div><p className="eyebrow">Talent pipeline</p><h2>Candidate applications</h2></div><p>{applications.length} people are waiting for your review</p></div>{applications.length ? <div className="candidate-grid">{applications.map((app) => <article className="candidate-card" key={app._id}><div className="avatar">{app.applicant?.name?.slice(0, 1) || "?"}</div><div className="candidate-info"><h3>{app.applicant?.name || "Applicant"}</h3><p>Applied for <b>{app.job?.title}</b></p><p className="muted">{app.applicant?.location || "Location unavailable"}</p>{app.resume && <a href={app.resume} target="_blank" rel="noreferrer">Open resume ↗</a>}</div><select value={app.status} onChange={(e) => status(app._id, e.target.value)}>{["applied", "shortlisted", "rejected", "accepted"].map((value) => <option key={value}>{value}</option>)}</select></article>)}</div> : <div className="empty candidate-empty">Applications will appear here as candidates apply.</div>}</section></section>;
}
