import { useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import api from "../services/api";

export default function JobApplication() {
  const { id } = useParams(); const { state } = useLocation(); const navigate = useNavigate(); const job = state?.job;
  const [resume, setResume] = useState(null); const [coverLetter, setCoverLetter] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const submit = async (e) => { e.preventDefault(); setError(""); setMessage(""); if (!localStorage.getItem("token")) return navigate("/login"); if (!resume || !coverLetter.trim()) return setError("Attach a PDF resume and write a cover letter."); if (resume.type !== "application/pdf") return setError("Your resume must be a PDF file."); if (resume.size > 5 * 1024 * 1024) return setError("Your resume must be 5 MB or smaller."); setLoading(true); try { const formData = new FormData(); formData.append("jobId", id); formData.append("resume", resume); formData.append("coverLetter", coverLetter.trim()); await api.post("/applications", formData); setMessage("Application submitted successfully!"); setResume(null); setCoverLetter(""); e.target.reset(); } catch (err) { setError(err.response?.data?.message || "Failed to submit application"); } finally { setLoading(false); } };
  return <section className="page narrow"><button className="back-link" onClick={() => navigate(`/jobs/${id}`)}>← Back to job</button><p className="eyebrow">Your application</p><h1>Put your best foot forward.</h1>{job && <div className="card application-job"><strong>{job.title}</strong><span>{job.company} · {job.location}</span></div>}<form className="card form-grid application-form" onSubmit={submit}>{message && <p className="alert success">{message}</p>}{error && <p className="alert error">{error}</p>}<label className="full">Resume <small>PDF only, maximum 5 MB</small><input type="file" accept="application/pdf,.pdf" required onChange={(e) => setResume(e.target.files?.[0] || null)} />{resume && <span className="file-name">Attached: {resume.name}</span>}</label><label className="full">Cover letter<textarea rows="9" required value={coverLetter} onChange={(e) => setCoverLetter(e.target.value)} placeholder="Briefly explain why you are a strong fit for this role." /></label><button className="button" disabled={loading}>{loading ? "Submitting…" : "Submit application"}</button></form></section>;
}
